### ISSUE TITLE
IBM cloud -watson text translator lost words ?

### ISSUE THREAD

**Issue by Roehse** [ibm-cloud-docs/language-translator#77] opened 2019-09-20 09:36 UTC
I'm not sure what happen but I use the IBM cloud - Demo: Translate text from the page  [IBM cloud - Demo](https://language-translator-demo.ng.bluemix.net/?_ga=2.42118503.314537322.1568831351-883329548.1568270463&cm_mc_uid=43081260652915682704623&cm_mc_sid_50200000=35675701568970809541) the translation lost 4 words any idea what happen? As you see I copied the translated text again in the source to check the result.
Thanks in advanced
Joerg
![English - Japanese](https://user-images.githubusercontent.com/36770996/65316334-0c573880-db9a-11e9-9b03-8052173f018a.jpg)
![Japanese - English](https://user-images.githubusercontent.com/36770996/65316335-0c573880-db9a-11e9-91ed-ca1617d0c669.jpg)

**Comment by SirSpidey** [comment] 2020-06-21 22:28
issue with demo, not the docs. closing

**Closed by SirSpidey** 2020-06-21 22:28 UTC

**Comment by Roehse** [comment] 2020-06-22 06:02
Hi, Sir Spidey, 
strange reason for the closure, The problem is not to be investigated or solved and... and so from where I stand, that is incomprehensible. 
The demo is probably part of the documentation page, so reopen this issue.
Same like you comment for my #71 ..."This repo is for the documentation, not for the service. Closing because no on addressed this last year."

**Comment by SirSpidey** [comment] 2020-06-22 12:19
@roehse, glad to see that there is someone on the other end of these old issues (old because didn't address). The demo is quite different now, so I don't think we can reproduce this. If you have issues with the service, see my comment in #71 for possible places to ask your questions.
